# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
