# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_backlogs',
            field=models.IntegerField(default=1),
        ),
    ]
