# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile_current_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rollno',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
