# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170419_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_backlogs',
            field=models.IntegerField(default=1),
        ),
    ]
