# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=30)),
                ('student_applied_job', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('company', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date_of_test', models.DateField(blank=True, null=True)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('minimum_backlogs', models.IntegerField(default=1)),
            ],
        ),
    ]
