# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('company', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('min_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
