# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_profile_current_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('student_applied_job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_applied_job', models.CharField(blank=True, max_length=50)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(unique=True)),
                ('company', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
