# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='min_cgpa',
            new_name='minimum_cgpa',
        ),
    ]
