# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170419_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='student_profile',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='student_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
