# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile_current_cgpa'),
        ('job', '0002_auto_20170406_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('student_rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile')),
            ],
        ),
    ]
