# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_appliedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='student_rollno',
            new_name='student_profile',
        ),
    ]
