# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_minimum_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_of_test',
            field=models.DateField(blank=True, null=True),
        ),
    ]
